### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by enrique89** [robvanoostenrijk/BrcmPatchRAM#4]
Hello, @doktordok referred your program to me based on the issue (https://github.com/dokterdok/Continuity-Activation-Tool/issues/122) I was having with my Asus BT-400 dongle not allowing me to correctly pair my Apple keyboard and trackpad after running the Continuity Activation Tool. 

I followed your instructions regarding putting the kext file in the System extensions folder, but I received the following error message. I'm including some screenshots for your information. Please let me know if there's anything else you need. I installed Clover but am not really sure how it works -- I apologize; I'm not a developer, I was just trying to get Continuity/Handoff to work on my early 2011 MBP, which it now does, but now I've lost configuration of my keyboard and trackpad.

Thanks for any insight or help you can provide.

![2015-01-07 06 47 04 pm](https://cloud.githubusercontent.com/assets/10439420/5655624/209bc28e-969e-11e4-9e92-c408510699d3.png)

![2015-01-07 06 47 46 pm](https://cloud.githubusercontent.com/assets/10439420/5655626/2434c7ce-969e-11e4-9ccf-506d822b86d2.png)

![2015-01-07 06 48 04 pm](https://cloud.githubusercontent.com/assets/10439420/5655629/27390b10-969e-11e4-9772-f47d6c84f6f6.png)

**Comment by robvanoostenrijk** [comment]
Ok first things first.

The instructions in the readme are for a [Hackintosh](http://en.wikipedia.org/wiki/OSx86). That is a PC modified to run Mac OS X.

You should _not_ install Clover on a real Mac as it might inadvertently break things.
Ensure you remove Clover from your boot drive or ESP, wherever you installed it.

Now BrcmPatchRAM.kext is indeed a kernel extension. However its an unsigned kernel extension (Apple obviously would not approve of these extensions).

In order to use it you need to enable unsigned kernel extensions, for that run the following command in the terminal:
```
sudo nvram boot-args
``` 

Take note of the boot-args output.

To the existing value (if any, it could well be empty) concatenate "kext-dev-mode=1"
So if it was empty (default) you would execute:
```
sudo nvram boot-args="kext-dev-mode=1"
```

Now reboot the Mac. You can now install BrcmPatchRAM inside /System/Library/Extensions.
Run the following in the command prompt:
```
touch /System/Library/Extensions
```

Wait about a minute before rebooting the Mac again.

If all works properly you will notice that the firmware version in the Bluetooth profiler will now show a higher version than v4096 (4096 means its non-upgraded).

Additionally you can confirm BrcmPatchRAM did its job by running the following in the terminal:
```
sudo cat /var/log/system.log | grep -i brcm[fp]
```

This will show you an log excerpt of BrcmPatchRAM output during startup.

**Comment by robvanoostenrijk** [comment]
Seeing your question I have now updated the main readme to link to an additional instruction set for original Mac owners.

**Comment by dokterdok** [comment]
@enrique89 I used the following steps to install BrcmPatchRAM.kext:

1. Download and install [KextDrop](http://www.cindori.org/software/kextdrop)
2. Open it
3. Drag and drop BrcmPatchRAM.kext in it, click install 
4. Reboot

In your case you don't need to apply the terminal commands mentioned by Rob, as CAT did the work already when it did the activation on your machine.

**Comment by enrique89** [comment]
@robvanoostenrijk and @dokterdok: Thank you both very much for your clear and prompt replies! I was able to use @dokterdok's suggested KextDrop program to install your kext and have verified that the Bluetooth firmware is updated. I am now able to correctly pair and control my Apple keyboard and trackpad, and have maintained the Continuity & Handoff features from CAT to boot! 

Regarding uninstalling Clover...I just deleted the related folders from my Macintosh SSD folder. I had to authenticate but that was it. I hope that's the correct way of uninstalling? If not, would you mind terribly to correct my misunderstanding?

**Comment by robvanoostenrijk** [comment]
@enrique89, Great to hear everything is working fine.
Thanks to your feedback there is now an additional instructional page for Mac users.

And yes, that should get rid of Clover just fine.
